cv_reader_task:
  description: >
    Extract relevant information from the given CV. Focus on skills, experience,
    education, and key achievements.
    Ensure to capture the candidate's professional summary, technical skills,
    work history, and educational background.
     
    CV file: {cv_path}
  expected_output: >
     A structured summmary of hte CV having following values
      - Professional Summary
      - Professional Experience
      - Skills
      - Education
      - Projects
      - Country Name
      - Key Achivement 

  agent: cv_reader
